kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: ${namespace}
  name: ${network_policy_name}
spec:
  podSelector:
    matchLabels: {}
  ingress:
  - from:
    - podSelector: {}
